In [42]:
from pandas import *
import numpy as np
import sys
data = read_excel('cleaned_data.xlsx')

In [19]:
data2 = data.loc[data['gender']!=3,]
data3 = data2.loc[data['gender']!=4,]
data4 = data3.loc[data['gender']!='미상',]
data5 = data4.loc[data['gender']!=' ',]
data6 = data5.loc[data['gender']!=210,]
data6 = data6

In [9]:
unique(data6['gender'])

array([2, 1, '여자', '남자'], dtype=object)

In [10]:
unique(data6['age'])

array([ 101,  132,  126,  122,  124,  112,  110,  159,  137,  144,  129,
        145,  146,  125,  102,  166,  135,  128,  104,  210,  100,  105,
        103,  179,  172,  115,  106,  170,  155,  139,  148,  160,  118,
        134,  136,  140,  174,  149,  150,  156,  109,  130,  127,  143,
        123,  168,  161,  152,  164,  167,  154,  165,  141,  147,  171,
        151,  114,  157,  173,  180,  175,  142,  178,  131,  138,  117,
        158,  153,  116,  162,  108,  133,  163,  120,  121,  169,  107,
        113,  119,  176,  185,  177,  111,  182,  181,  189,  186,  184,
        191,  187,  190,  183,  188,  193,  192,  300,  196,  195,  194,
       1145,  199,  198,  197,  -76,  -96,  -25,  -62,  -71,  -98,  -65,
       -100,  -40,  -99,  -87,  -95,  -94,  -91,  -44,  -70,  -59,  -92,
        -55,  -90,  -97,  -73,  -93,  -45,  -18,  -75,  -61,  -51,  -88,
        -77,  -39,  -56,  -23,  -32,  -74,  -20,  -84,  -86,  -68,  -63,
        -67,  -42,  -89,  -50,  -31,  -49,  -29,  -

In [35]:
cleaned_age = []
for i in data6['age']:
    if (i > 100) & (i < 200):
        cleaned_age.append(i - 100)
    else:
        cleaned_age.append(i)

In [13]:
unique(cleaned_age)

array([   1,   32,   26,   22,   24,   12,   10,   59,   37,   44,   29,
         45,   46,   25,    2,   66,   35,   28,    4,  210,  100,    5,
          3,   79,   72,   15,    6,   70,   55,   39,   48,   60,   18,
         34,   36,   40,   74,   49,   50,   56,    9,   30,   27,   43,
         23,   68,   61,   52,   64,   67,   54,   65,   41,   47,   71,
         51,   14,   57,   73,   80,   75,   42,   78,   31,   38,   17,
         58,   53,   16,   62,    8,   33,   63,   20,   21,   69,    7,
         13,   19,   76,   85,   77,   11,   82,   81,   89,   86,   84,
         91,   87,   90,   83,   88,   93,   92,  300,   96,   95,   94,
       1145,   99,   98,   97,  -76,  -96,  -25,  -62,  -71,  -98,  -65,
       -100,  -40,  -99,  -87,  -95,  -94,  -91,  -44,  -70,  -59,  -92,
        -55,  -90,  -97,  -73,  -93,  -45,  -18,  -75,  -61,  -51,  -88,
        -77,  -39,  -56,  -23,  -32,  -74,  -20,  -84,  -86,  -68,  -63,
        -67,  -42,  -89,  -50,  -31,  -49,  -29,  -

In [37]:
cleaned_age2 = []
for j in cleaned_age:
    if j < 0:
        cleaned_age2.append(j +100)
    else:
        cleaned_age2.append(j)


In [16]:
unique(cleaned_age2)

array([   1,   32,   26,   22,   24,   12,   10,   59,   37,   44,   29,
         45,   46,   25,    2,   66,   35,   28,    4,  210,  100,    5,
          3,   79,   72,   15,    6,   70,   55,   39,   48,   60,   18,
         34,   36,   40,   74,   49,   50,   56,    9,   30,   27,   43,
         23,   68,   61,   52,   64,   67,   54,   65,   41,   47,   71,
         51,   14,   57,   73,   80,   75,   42,   78,   31,   38,   17,
         58,   53,   16,   62,    8,   33,   63,   20,   21,   69,    7,
         13,   19,   76,   85,   77,   11,   82,   81,   89,   86,   84,
         91,   87,   90,   83,   88,   93,   92,  300,   96,   95,   94,
       1145,   99,   98,   97,    0,  449])

In [43]:
new_data = DataFrame(data6)
new_data.to_excel(sys.path[1]+'/cleaned_data0305.xlsx')

In [41]:
for i in range(0,len(new_data['age'])):
    new_data.loc[i,'cleaned_age'] = int(cleaned_age2[i])
    if i%10000 == 0:
        print(i)

0


10000


20000


30000


40000


50000


60000


KeyboardInterrupt: 

In [40]:
print(len(new_data['age']))
print(len(data6['age']))
print(len(cleaned_age))
print(len(cleaned_age2))


297711
297711
297711
297711


In [27]:
unique(new_data['cleaned_age'])

array([  1.00000000e+00,   3.20000000e+01,   2.60000000e+01,
         2.20000000e+01,   2.40000000e+01,   1.20000000e+01,
         1.00000000e+01,   5.90000000e+01,   3.70000000e+01,
         4.40000000e+01,   2.90000000e+01,   4.50000000e+01,
         4.60000000e+01,   2.50000000e+01,   2.00000000e+00,
         6.60000000e+01,   3.50000000e+01,   2.80000000e+01,
         4.00000000e+00,   2.10000000e+02,   1.00000000e+02,
         5.00000000e+00,   3.00000000e+00,   7.90000000e+01,
         7.20000000e+01,   1.50000000e+01,   6.00000000e+00,
         7.00000000e+01,   5.50000000e+01,   3.90000000e+01,
         4.80000000e+01,   6.00000000e+01,   1.80000000e+01,
         3.40000000e+01,   3.60000000e+01,   4.00000000e+01,
         7.40000000e+01,   4.90000000e+01,   5.00000000e+01,
         5.60000000e+01,   9.00000000e+00,   3.00000000e+01,
         2.70000000e+01,   4.30000000e+01,   2.30000000e+01,
         6.80000000e+01,   6.10000000e+01,   5.20000000e+01,
         6.40000000e+01,